package(default_visibility = ["//visibility:public"])

cc_library(
    name = "clientlib",
    srcs = ["greeter_client.cc"],
    hdrs = ["greeter_client.h"],
    deps = ["//examples/helloworld/proto:cpp"],
)