package_group(
    name = "visibility",
    packages = ["//java/..."],
)

java_binary(
    name = "client",
    main_class = "ro.dragossusi.grpc.linuxcnc.MainKt",
    runtime_deps = [
        "//java/ro/dragossusi/grpc/linuxcnc",
    ],
)
