load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "command_writer",
    srcs = ["command_writer.cc"],
    hdrs = ["command_writer.hh"],
    copts = [
        "-Iexternal/linuxcnc/include",
        "-Iexternal/linuxcnc/src",
    ],
    defines = ["BAZEL_BUILD"],
    visibility = ["//visibility:public"],
    deps = [
        "//third_party/linuxcnc",
        "@linuxcnc_proto//proto/linuxcnc:linuxcnc_cc_grpc",
    ],
)
